# Generated by Django 5.2.10 on 2026-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('expire', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
